### ISSUE TITLE
Deno lock file?

### ISSUE THREAD

**Issue by dhess** [moosingin3space/nur-packages#3]
Hi, thanks for experimenting with Nix packaging for Deno.

How did you generate the `lock.json` file for Velociraptor in your example?

*edit* Ahh, something like this works: 

```sh
deno run --lock lock.json --lock-write -A https://deno.land/x/package/foo.ts
```

Any idea how to do this directly from a GitHub repo/archive; e.g., if the package is private or you want to use a version that's not been published to deno.land yet?

*edit #2* This seems to do the trick for Aleph, at least:

```sh
deno cache  --lock lock.json --lock-write https://raw.githubusercontent.com/alephjs/aleph.js/master/cli.ts
```

**Comment by moosingin3space** [comment]
Hi! I'm glad to see someone else is interested, as I plan to submit a PR to nixpkgs adding this.

To be exact, I cloned Velociraptor's github repo and checked out the revision I've set in the Nix expression, then I manually ran `deno cache --lock lock.json --lock-write ./cli.ts`.

**Comment by moosingin3space** [comment]
Closing as there's no action here.
